name: ChunkNorris CI/CD

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master # Trigger on PRs targeting the main branch
  release:
    types: [published] # Trigger on a new release being published

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo test
        run: cargo test --verbose

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test # Only run if the test job passes
    if: github.event_name == 'release' && github.event.action == 'published' # Only run on published releases
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: cargo build --release
      - uses: katyo/publish-crates@v2
        with:
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
